In [1]:
%matplotlib notebook

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
#import seaborn as sb

In [3]:
countries_subset = ['Japan',
            'South Korea', # Korea, Dem. Peopleâ€™s Rep.
            'United Kingdom',
            'Singapore',
            'Russia', # Russian Federation
            'Finland',
            'Canada',
            'Netherlands',
            'Ireland',
            'Israel',
            'China',
            'New Zealand',
            'Norway',
            'Belgium',
            'Germany',
            'Denmark',
            'Estonia',
            'United States',
            'France',
            'Portugal']

In [4]:
# File to Load (Remember to change these)
OWID_life_expectancy_csv_path = "data_sources/OWID_life-expectancy.csv"

# Read in the data from the CSV
OWID_life_expectancy_data = pd.read_csv(OWID_life_expectancy_csv_path)

# convert data to a DataFrame
OWID_life_expectancy_df = pd.DataFrame(OWID_life_expectancy_data)

#OWID_life_expectancy_df.head()
#OWID_life_expectancy_df["Entity"].unique()

country_subset_life_expectancy = OWID_life_expectancy_df.loc[(OWID_life_expectancy_df["Entity"].isin(countries_subset)),:]

countries_and_codes_subset = country_subset_life_expectancy[["Entity","Code"]].drop_duplicates().rename(columns={"Entity":"country","Code":"country_code"})

countries_and_codes_subset

# Save path to store output file set in a variable
csv_output = "data_exports/countries_and_codes_20Countries.csv"

# Export file as a CSV, without the Pandas index, 
# but with the header
countries_and_codes_subset.to_csv(csv_output, index=False, header=True)

              country country_code
1321          Belgium          BEL
2373           Canada          CAN
3020            China          CHN
3853          Denmark          DNK
4724          Estonia          EST
4992          Finland          FIN
5143           France          FRA
5673          Germany          DEU
7164          Ireland          IRL
7236           Israel          ISR
7581            Japan          JPN
10952     Netherlands          NLD
11184     New Zealand          NZL
11727          Norway          NOR
12638        Portugal          PRT
12979          Russia          RUS
13735       Singapore          SGP
14200     South Korea          KOR
16543  United Kingdom          GBR
16777   United States          USA